---
title: "offline_stream_history"
author: "Justyn"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(jsonlite)
library(lubridate)
library(gghighlight)
#library(spotifyr) #don't need for this
library(tidyverse)
library(knitr)
library(ggplot2)
library(plotly)
```

## Including Plots

Copy of your data from Spotify
```{r}
streamHistory <- fromJSON("C:/Users/justy/Downloads/spotify-main/spotify-main/StreamingHistory0.json", flatten = TRUE)

head(streamHistory)
```

## Tidy the Data

Check for missing data
```{r}
sum(is.na(streamHistory))
```



Here you combined the total play time before you reduced it.
```{r}
head(mySpotify1)

mySpotify <- streamHistory %>%
  mutate_at("endTime", ymd_hm) %>%
  mutate(endTime = endTime - hours(6)) %>%
  mutate(date = floor_date(endTime, "day") %>%
           as_date, seconds = msPlayed / 1000, minutes = seconds / 60) %>%
  group_by(artistName, trackName) %>%
  mutate(totalTime = sum(msPlayed)) %>% #in ms
  add_count(trackName, name = "playCount") %>%
  distinct(trackName, .keep_all = TRUE) %>%
  dplyr::ungroup(artistName, trackName)

```


```{r}
mySpotify <- mySpotify %>%
  relocate(endTime, .after = minutes) %>%
  relocate(playCount, .after = artistName) %>%
  relocate(trackName, .before = artistName) %>%
  relocate(totalTime, .before = endTime) %>%
  relocate(date, .after = totalTime)
```



Artist DF with
ArtistName
Total time MS
Total time minutes
Total artist playcount
```{r}
mySpotifyArtist <- streamHistory %>%
   mutate_at("endTime", ymd_hm) %>%
  mutate(endTime = endTime - hours(6)) %>%
  mutate(date = floor_date(endTime, "day") %>%
           as_date, seconds = msPlayed / 1000, minutes = seconds / 60)


mySpotifyArtist <- mySpotifyArtist %>%
  group_by(artistName) %>%
  summarise(totaltimeMS = sum(msPlayed), totalTimeMinutes = sum(minutes), totalPlays = n()) %>%
  arrange(-totalPlays)
  
  
```









```{r}

```




